'addon: info': ['shilman', 'elevatebart']
typescript: ['kroeder', 'gaetanmaisse', 'ndelangen', 'emilio-martinez']
dependencies: ['ndelangen']
'babel / webpack': ['ndelangen', 'igor-dv', 'shilman']
'yarn / npm': ['ndelangen', 'tmeasday']
