version: 2.1

aliases:
  - &defaults
    working_directory: /tmp/storybook
    docker:
      - image: circleci/node:10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore core dependencies cache
          keys:
            - core-dependencies-v4-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Check that yarn.lock is not corrupted
          command: yarn repo-dirty-check
      - run:
          name: Bootstrap
          command: yarn bootstrap --core
      - save_cache:
          name: Cache core dependencies
          key: core-dependencies-v4-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
            - /root/.cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - examples
            - addons
            - dev-kits
            - app
            - lib
  chromatic:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run chromatic on the pre-built official example
          command: yarn chromatic --storybook-build-dir="built-storybooks/official-storybook" --exit-zero-on-changes --app-code="ab7m45tp9p"

  examples:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: examples
          command: |
            yarn build-storybooks
      - persist_to_workspace:
          root: .
          paths:
            - built-storybooks
  smoke-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run official-storybook (smoke test)
          command: |
            cd examples/official-storybook
            yarn storybook --smoke-test --quiet

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test --coverage --w2 --core
      - persist_to_workspace:
          root: .
          paths:
            - coverage
  coverage:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Upload coverage
          command: yarn coverage
workflows:
  test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - examples:
          requires:
            - build
      - smoke-tests:
          requires:
            - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      - chromatic:
          requires:
            - examples
